services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pipelinex-api
    ports:
      - "8000:8000"
    environment:
      - DUCKDB_PATH=/app/data/warehouse.duckdb
      - CSV_PATH=/app/data/raw/transactions.csv
    volumes:
      - api-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pipelinex-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: pipelinex-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=7d"
    depends_on:
      - api
    restart: always

  grafana:
    image: grafana/grafana:10.4.1
    container_name: pipelinex-grafana
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/finsight.json
    depends_on:
      - prometheus
    restart: always

volumes:
  api-data:
  prometheus-data:
  grafana-data:
